source("scripts/01_acquire_data.R")
source("scripts/02_clean_text.R")
source("scripts/02b_enrich_metadata.R")
source("scripts/03_build_dictionary.R")
source("scripts/04_score_bbi.R")
source("scripts/05_visualize.R")
source("scripts/06_model.R")
source("scripts/07_validate.R")

message("BBI pipeline complete.")
